language: node_js
node_js: 7
script:
- echo "Deploy!"
install:
- npm install -g firebase-tools
after_success:
- firebase deploy -project devfestperm -token 1/EFEs2Dilnegsg8AmcwPcbRrQ8VRhfdMrtWLd3UY3PyA
